package fr.covea.poc;

import fr.covea.poc.model.Person;
import fr.covea.poc.service.PersonService;
import jakarta.inject.Inject;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.NotFoundException;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.parameters.Parameter;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

import java.net.URI;
import java.util.Collection;

@Path("/persons")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Tag(
        name = "Persons",
        description = "Operations for managing insured persons, policy holders, claimants and contacts."
)
public class PersonResource {

    @Inject
    PersonService personService;

    @GET
    @Operation(
            summary = "List all persons",
            description = "Returns the complete list of persons currently stored in memory. This endpoint is intended for mock and demonstration purposes."
    )
    @APIResponse(
            responseCode = "200",
            description = "List of persons successfully returned",
            content = @Content(schema = @Schema(implementation = Person.class))
    )
    public Collection<Person> getAll() {
        return personService.all();
    }

    @GET
    @Path("{id}")
    @Operation(
            summary = "Get a person by identifier",
            description = "Returns the person matching the provided technical identifier. If no person exists for this identifier, a 404 response is returned."
    )
    @APIResponse(
            responseCode = "200",
            description = "Person successfully found",
            content = @Content(schema = @Schema(implementation = Person.class))
    )
    @APIResponse(
            responseCode = "404",
            description = "No person exists for the provided identifier"
    )
    public Person getById(
            @Parameter(
                    description = "Technical identifier of the person to retrieve.",
                    required = true,
                    example = "1"
            )
            @PathParam("id") int id
    ) {
        Person person = personService.get(id);

        if (person == null) {
            throw new NotFoundException("Person not found with id: " + id);
        }

        return person;
    }

    @POST
    @Operation(
            summary = "Create a person",
            description = "Creates a new person in the in-memory repository. The identifier provided in the request body is ignored and replaced by a generated identifier."
    )
    @APIResponse(
            responseCode = "201",
            description = "Person successfully created",
            content = @Content(schema = @Schema(implementation = Person.class))
    )
    public Response create(
            @Parameter(
                    description = "Person information to create. The id field is generated by the API.",
                    required = true
            )
            Person person
    ) {
        Person createdPerson = personService.create(person);

        return Response
                .created(URI.create("/persons/" + createdPerson.getId()))
                .entity(person)
                .build();
    }

    @PUT
    @Path("{id}")
    @Operation(
            summary = "Update a person",
            description = "Replaces the existing person matching the provided identifier with the payload content. The path identifier is authoritative and overrides the id from the request body."
    )
    @APIResponse(
            responseCode = "200",
            description = "Person successfully updated",
            content = @Content(schema = @Schema(implementation = Person.class))
    )
    @APIResponse(
            responseCode = "404",
            description = "No person exists for the provided identifier"
    )
    public Person update(
            @Parameter(
                    description = "Technical identifier of the person to update.",
                    required = true,
                    example = "1"
            )
            @PathParam("id") int id,
            @Parameter(
                    description = "Updated person information.",
                    required = true
            )
            Person person
    ) {
        Person updatedPerson = personService.update(id, person);
        if (updatedPerson == null) {
            throw new NotFoundException("Person not found with id: " + id);
        }

        return updatedPerson;
    }

    @DELETE
    @Path("{id}")
    @Operation(
            summary = "Delete a person",
            description = "Deletes the person matching the provided identifier from the in-memory repository."
    )
    @APIResponse(
            responseCode = "204",
            description = "Person successfully deleted"
    )
    @APIResponse(
            responseCode = "404",
            description = "No person exists for the provided identifier"
    )
    public Response delete(
            @Parameter(
                    description = "Technical identifier of the person to delete.",
                    required = true,
                    example = "1"
            )
            @PathParam("id") int id
    ) {
        Person removedPerson = personService.remove(id);

        if (removedPerson == null) {
            throw new NotFoundException("Person not found with id: " + id);
        }

        return Response.noContent().build();
    }
}
